### PR TITLE
Repeat `NettyConnectorFactory` for each host

### LINKED ISSUE #567: unable to connect to cluster if first node is down
# problem description
I have created a quarkus app connecting to a hornetq cluster, and sending a message every 5 seconds.
if both hornetq nodes are up, and I start the application, I can send my messages OK.
if I shut down node `x1`, and I start the application, no messages get sent at all, and the following exception gets logged every time the scheduler gets called, and no messages get sent:

```
2024-07-23 15:50:37,869 INFO  [io.qua.iro.runtime] (jca-worker-pool-<default>-1) QIJ000001: Starting Resource Adapter <default>: ActiveMQ Artemis 2.33.0

2024-07-23 15:50:37,884 INFO  [org.apa.act.art.ra.ActiveMQRALogger] (jca-worker-pool-<default>-1) AMQ151007: Resource adaptor started
2024-07-23 15:50:38,041 INFO  [io.quarkus] (Quarkus Main Thread) jmsraavail 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.12.3) started in 3.446s. Listening on: http://localhost:18080                                              
2024-07-23 15:50:38,042 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-07-23 15:50:38,043 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [artemis-core, artemis-jms-ra, cdi, ironjacamar, narayana-jta, quartz, rest, scheduler, smallrye-context-propagation, vertx]    
...              
2024-07-23 15:50:40,145 WARN  [org.jbo.jca.cor.con.poo.str.PoolByCri] (vert.x-worker-thread-1) IJ000604: Throwable while attempting to get a new connection: null: jakarta.resource.ResourceException: Failed to create session factory
        at org.apache.activemq.artemis.ra.ActiveMQRAManagedConnection.setup(ActiveMQRAManagedConnection.java:725)
        at org.apache.activemq.artemis.ra.ActiveMQRAManagedConnection.<init>(ActiveMQRAManagedConnection.java:161)
        at org.apache.activemq.artemis.ra.ActiveMQRAManagedConnectionFactory.createManagedConnection(ActiveMQRAManagedConnectionFactory.java:144)
        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:1267)
        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:495)
        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getTransactionNewConnection(AbstractPool.java:770)
        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:666)
        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:624)
        at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:440)
        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:789)
        at org.apache.activemq.artemis.ra.ActiveMQRASessionFactoryImpl.allocateConnection(ActiveMQRASessionFactoryImpl.java:792)
        at org.apache.activemq.artemis.ra.ActiveMQRASessionFactoryImpl.createSession(ActiveMQRASessionFactoryImpl.java:482)
        at org.apache.activemq.artemis.ra.ActiveMQRASessionFactoryImpl.createSession(ActiveMQRASessionFactoryImpl.java:673)
        at org.apache.activemq.artemis.ra.ActiveMQRASessionFactoryImpl.createSession(ActiveMQRASessionFactoryImpl.java:678)
        at org.apache.activemq.artemis.ra.ActiveMQRAConnectionFactoryImpl.validateUser(ActiveMQRAConnectionFactoryImpl.java:422)
        at org.apache.activemq.artemis.ra.ActiveMQRAConnectionFactoryImpl.createContext(ActiveMQRAConnectionFactoryImpl.java:379)
        at org.apache.activemq.artemis.ra.ActiveMQRAConnectionFactoryImpl.createContext(ActiveMQRAConnectionFactoryImpl.java:369)
        at org.apache.activemq.artemis.ra.ActiveMQRAConnectionFactoryImpl.createContext(ActiveMQRAConnectionFactoryImpl.java:364)
        at org.acme.MyProducer.send(MyProducer.java:40)
        at org.acme.MyProducer_Subclass.send$$superforward(Unknown Source)
        at org.acme.MyProducer_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at org.acme.MyProducer_Subclass.send(Unknown Source)
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:915)
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createXAConnection(ActiveMQConnectionFactory.java:387)
        at org.apache.activemq.artemis.ra.ActiveMQRAManagedConnection.setup(ActiveMQRAManagedConnection.java:713)
        ... 49 more
Caused by: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ219007: Cannot connect to server(s). Tried with all available servers.]
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:735)
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:913)
        ... 51 more
```

The application has the following configuration:
```
quarkus.http.port=18080
quarkus.ironjacamar.ra.kind=artemis
quarkus.ironjacamar.ra.config.connection-parameters=host=x1;port=...,host=x2;port=...;protocols=CORE
quarkus.ironjacamar.ra.config.protocol-manager-factory=org.apache.activemq.artemis.core.protocol.hornetq.client.HornetQClientProtocolManagerFactory
quarkus.ironjacamar.ra.config.user=...
quarkus.ironjacamar.ra.config.password=...
quarkus.ironjacamar.activation-spec.myqueue.config.destination-type=jakarta.jms.Queue
quarkus.ironjacamar.activation-spec.myqueue.config.destination=jms.queue....
quarkus.ironjacamar.activation-spec.myqueue.config.max-session=10
quarkus.ironjacamar.activation-spec.myqueue.config.rebalance-connections=true
```

if I exchange `x1` and `x2` then it works:
```
quarkus.ironjacamar.ra.config.connection-parameters=host=x2;port=...,host=x1;port=...;protocols=CORE
```

this only fails when the failed node is first in the url.

# expectation

the client should be able to connect to any running node.

# producer code
```
@ApplicationScoped
public class MyProducer {

    private static final Logger log = LoggerFactory.getLogger(MyProducer.class);

    public static final String QUEUE = "jms.queue.com.lodh.jee.ArteTest.Bank.jms.bankref1.QueueB";

    private final Queue queue = ActiveMQDestination.createQueue(QUEUE);;

    @Inject
    ConnectionFactory factory;

    @Scheduled(every = "5s")
    public void send() throws UnknownHostException {
        try (JMSContext context = factory.createContext()) {
            String text = new Date() + " from host=" + InetAddress.getLocalHost().getHostName();
            log.info("sending jms message {}", text);
            JMSProducer producer = context.createProducer();
            TextMessage message = context.createTextMessage(text);
            producer.send(queue, message);
        }
    }
}
```

# pom
```
<quarkus.platform.version>3.12.3</quarkus.platform.version>
...
    <dependency>
      <groupId>io.quarkiverse.artemis</groupId>
      <artifactId>quarkus-artemis-jms-ra</artifactId>
      <version>3.3.0</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-scheduler</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>artemis-hqclient-protocol</artifactId>
      <version>2.33.0</version>
    </dependency>
```

cc @gastaldi @zhfeng

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #567

### CODE REVIEW

**Comment by turing85** [comment]
@zhfeng do you have time to review this change?

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ public String getProductVersion() {
     @Override
     public ActiveMQResourceAdapter createResourceAdapter(String id, Map<String, String> config) {
         ActiveMQResourceAdapter adapter = new ActiveMQResourceAdapter();
-        adapter.setConnectorClassName(NettyConnectorFactory.class.getName());
+        adapter.setConnectorClassName(config.getOrDefault("connector-class-name", NettyConnectorFactory.class.getName()));
```
Comment (zhfeng) [inline ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:46]: @gastaldi @vsevel IIUC, there could be multi ConnectorClassName if more than two hosts are configured. Then I wonder the default valude of `connector-class-name` might be `NettyConnectorFactory` * the number of hosts?

File: docs/modules/ROOT/pages/includes/attributes.adoc
Comment (zhfeng) [inline docs/modules/ROOT/pages/includes/attributes.adoc:1]: It could be better to take  these change in `.adoc` in a seperated commit.

File: docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
Comment (zhfeng) [inline docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc:1]: the same here.

File: docs/modules/ROOT/pages/includes/attributes.adoc
Comment (gastaldi) [reply docs/modules/ROOT/pages/includes/attributes.adoc:1]: They are in a separated commit already, you mean a separated PR?

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 1 above)
Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:46]: I considered that too while creating the PR but I was hoping that you could use a different connector class here. OTOH I wasn't sure if this attribute should be configurable, so I took the easiest path 😀

File: docs/modules/ROOT/pages/includes/attributes.adoc
Comment (gastaldi) [reply docs/modules/ROOT/pages/includes/attributes.adoc:1]: Actually if you just build locally you should see the changes, want to do it and push to main directly?

Comment (zhfeng) [reply docs/modules/ROOT/pages/includes/attributes.adoc:1]: Oh, sorry, I missed it and looks good.

**Review by zhfeng — APPROVED** [review]

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 1 above)
Comment (vsevel) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:46]: additionally, one idea would be to complete the connector classname string to match the size of the connection parameters.
in other words if I set a connection parameters to set 2 hosts, by I include only one connector class name, then I would automatically add an additional connector class name, to match the number of hosts.
having to match both size is really error prone.

Comment (vsevel) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:46]: or log a warning, or throw an error.

Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:46]: Actually I kinda like @zhfeng 's suggestion. I think introducing a new parameter will require proper validation and I don't see a use case requiring it now BTW

Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java]: I went ahead and implemented @zhfeng's suggestion in [`62e01a9` (#572)](https://github.com/quarkiverse/quarkus-artemis/pull/572/commits/62e01a9201112665d8ba9bace7c8ca77cdfae306)

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java [hunk 2]
```diff
@@ -43,8 +43,19 @@ public String getProductVersion() {
...
+        // Repeat the NettyConnectorFactory class name for each host
+        String connectorClassName = NettyConnectorFactory.class.getName();
+        StringBuilder sb = new StringBuilder();
+        for (int i = 0; i < hosts; i++) {
+            if (i > 0) {
+                sb.append(",");
+            }
+            sb.append(connectorClassName);
+        }
+        adapter.setConnectorClassName(sb.toString());
```
Comment (turing85) [inline ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: WDYT?
```suggestion
        adapter.setConnectorClassName(IntStream.range(1, hosts)
            .mapToObj(unused -> connectorClassName)
            .collect(Collectors.joining(",")));
```

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java [hunk 3]
```diff
@@ -86,6 +97,14 @@ public MessageEndpoint wrap(MessageEndpoint endpoint, Object resourceEndpoint) {
         return new JMSMessageEndpoint(endpoint, (MessageListener) resourceEndpoint);
     }
 
+    private static int count(String text, String find) {
+        int count = 0, length = find.length();
+        for (int index = 0; (index = text.indexOf(find, index)) != -1; index += length) {
+            count++;
+        }
+        return count;
```
Comment (turing85) [inline ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:105]: I do not like the two variable declarations in one line.

Also, we could reduce this to an onleliner (and possibly inline the method):
```suggestion
        return text.split(find).length - 1;
```

 the `-1` in the `split(...)` call signals that trailing matches should not be discarded. This would be relevant if the `text` ends with `find`.

**Review by turing85 — CHANGES_REQUESTED** [review]
Both changes are suggestions. The only thing I'd really like seeing changed is the multi-variable declaration on a single line [here](https://github.com/quarkiverse/quarkus-artemis/pull/572/files#diff-67c6626fbcfb5eb404b2062039a67122a08b7850e95596c187fc224095bd25c8R101).

**Comment by turing85** [comment]
@all-contributors please add @gastaldi  for code

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 2 above)
Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: Not sure introducing lambdas here for something simple is a good thing, maybe for readability, but I have no objections if the team agrees on it

Comment (turing85) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: What exactly is the issue with the lambda?

Comment (middagj) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: I don't mind either. Since this is only run once we can prefer readability over performance. You can do `sb.append(',')` and skip the `if` and do a `subString(0, sb.length() - 1)` at the end.

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 3 above)
Comment (middagj) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:105]: `split` is a regex, so you need to escape.

Comment (turing85) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:105]: w.l.o.g.: yes
If we inline: no

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 2 above)
Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: > What exactly is the issue with the lambda?

It's a new class created in disk which gets instantiated and consumes memory
 
> Anyway, please do not treat this as a blocker. I tend to use streams for readability, but I am absolutely fine with keeping the loop.

+1

Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: Sorry, When we compile the lambda expression, an equivalent private static or non-static method is added to the bytecode, the information above is incorrect

Comment (zhfeng) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java:57]: Well, IIRC, this ResourceAdaptorFactory could be initilized at the build time. So I don't see much performance issues here. +1 for the lambda.

File: ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java (hunk 3 above)
Comment (gastaldi) [reply ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java]: I split the declaration into 2 lines, I'd prefer to keep the implementation as is, thanks

**Comment by vsevel** [comment]
this is the right approach to me.

**Review by vsevel — APPROVED** [review]

**Review by middagj — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Comment by vsevel** [comment]
I have tested, and I confirm this is fixing the original issue. thanks all.
